второй этап
anastasiaelis/diplom pull request #2
Opened 2024-08-18 13:08 UTC by anastasiaelis

2024-08-20 16:18 UTC, anastasiaelis commented
Привет!
Подскажи, пожалуйста, где можно искать проблему, чтобы приложение запустилось быстрее, чем за 60 с?

2024-08-21 12:02 UTC, VadimZharkov commented on docker-compose.yml
>      container_name: server
контейнер тоже stat-service назови, main-service будет ждать поднятого контейнера с именем stat-service и очевидно не может дождаться. Дело не в 60 сек.

2024-08-21 14:34 UTC, anastasiaelis commented on docker-compose.yml
>      container_name: server
не помогло(

2024-08-23 04:33 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/ewm/model/Category.java
> +@Data
Для сущностей в дипломной работе `@Data` не рекомендуется использовать. 
Здесь можно почитать почему https://jpa-buddy.com/blog/lombok-and-jpa-what-may-go-wrong/
Замени `@Data` на `@Getter и @Setter`  на всех сущностях, этого будет достаточно

2024-08-23 04:40 UTC, VadimZharkov requested changes
Хорошая работа, от меня одно замечание относительно  `@Data` и сущностей.

2024-08-24 04:42 UTC, VadimZharkov approved these changes

2024-08-24 06:00 UTC, merged